In [1]:
%pip install pandas matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in d:\ecommerce analytics\ecommerceenv\lib\site-packages (3.0.1)
Requirement already satisfied: matplotlib in d:\ecommerce analytics\ecommerceenv\lib\site-packages (3.10.8)
Requirement already satisfied: seaborn in d:\ecommerce analytics\ecommerceenv\lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in d:\ecommerce analytics\ecommerceenv\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.26.0 in d:\ecommerce analytics\ecommerceenv\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\ecommerce analytics\ecommerceenv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\ecommerce analytics\ecommerceenv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in d:\ecommerce analytics\ecommerceenv\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\ecommerce analytics\ecommerceenv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\ecommerce analytics\ecommerceenv\lib\site-packages (from matplotlib) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\ecommerce analytics\ecommerceenv\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in d:\ecommerce analytics\ecommerceenv\lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in d:\ecommerce analytics\ecommerceenv\lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in d:\ecommerce analytics\ecommerceenv\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in d:\ecommerce analytics\ecommerceenv\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in d:\ecommerce analytics\ecommerceenv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in d:\ecommerce analytics\ecommerceenv\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in d:\ecommerce analytics\ecommerceenv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import matplotlib as plt
import seaborn as sns

ecom = pd.read_csv('d:\\Ecommerce Analytics\\files\\ecommerce_data.csv')

In [4]:
ecom

,UserID,Username,FirstName,LastName,Email,Address,City,State,ZipCode,Country,...,Phone,PurchaseID,ProductName,Category,Price,Quantity,TotalAmount,PurchaseDate,PaymentMethod,Status
0,1,leo_robinson_704,Leo,Robinson,leo_robinson_704@example.com,819 Main St,Houston,NC,76672.0,France,...,(832)294-2916,1.0,Laptop,Electronics,43.21,1.0,43.21,2021-06-18,Bank Transfer,Pending
1,1,leo_robinson_704,Leo,Robinsontypo,leo_robinson_704@example.com,819 Main St,Houston,NC,76672.0,France,...,(832)294-2916,2.0,Puzzle,Toys,235.47,2.0,470.94,2022-11-02,Bank Transfer,Refunded
2,1,leo_robinson_704,Leo,Robinson,leo_robinson_704@example.com,819 Main St,Houston,NC,76672.0,France,...,(832)294-2916,3.0,Pants,Clothing,105.77,1.0,105.77,2021-09-06,Credit Card,Cancelled
3,1,leo_robinson_704,Leo,Robinson,leo_robinson_704@example.com,819 Main St,Houston,NC,76672.0,France,...,(832)294-2916,NaN,Biography,Books,290.19,2.0,580.38,2022-10-20,Credit Card,Refunded
4,1,leo_robinson_704,Leo,Robinson,leo_robinson_704@example.com,819 Main St,Houston,NC,76672.0,France,...,(832)294-2916,5.0,Camera,Electronics,344.09,2.0,688.18,2021-05-18,Bank Transfer,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2599,500,jack_rodriguez_661,Jack,NaN,jack_rodriguez_661@example.com,7734 Main St,Dallas,CA,37181.0,USA,...,(689)156-2407,2559.0,Board Game,Toys,61.19,3.0,183.57,2025-04-20,Credit Card,Completed
2600,500,jack_rodriguez_661,Jack,Rodriguez,jack_rodriguez_661@example.com,7734 Main St,Dallas,CA,37181.0,USA,...,(689)156-2407,2560.0,Dress,Clothing,226.90,1.0,226.90,2023-07-09,PayPal,Completed
2601,500,jack_rodriguez_661,Jack,Rodriguez,jack_rodriguez_661@example.com,7734 Main St,Dallas,CA,37181.0,USA,...,(689)156-2407,2561.0,Camera,Electronics,17.11,NaN,34.22,2023-12-14,Bank Transfer,Cancelled
2602,500,jack_rodriguez_661,Jack,Rodriguez,jack_rodriguez_661@example.com,7734 Main St,Dallas,CA,18.0,USA,...,(689)156-2407,2562.0,Camera,Electronics,65.95,5.0,NaN,2025-02-02,Debit Card,Cancelled
2603,500,jack_rodriguez_661,Jack,Rodriguez,jack_rodriguez_661@example.com,7734 Main St,Dallas,CA,37181.0,USA,...,(689)156-2407,2563.0,Puzzle,Toys,397.19,1.0,397.19,2024-05-09,Cash on Delivery,Refunded

In [5]:
ecom['Quantity'] = ecom['Quantity'].fillna(0)
ecom['PurchaseID'] = ecom['PurchaseID'].fillna(0)
ecom['PurchaseDate'] = pd.to_datetime(ecom['PurchaseDate'])

ecom

,UserID,Username,FirstName,LastName,Email,Address,City,State,ZipCode,Country,...,Phone,PurchaseID,ProductName,Category,Price,Quantity,TotalAmount,PurchaseDate,PaymentMethod,Status
0,1,leo_robinson_704,Leo,Robinson,leo_robinson_704@example.com,819 Main St,Houston,NC,76672.0,France,...,(832)294-2916,1.0,Laptop,Electronics,43.21,1.0,43.21,2021-06-18,Bank Transfer,Pending
1,1,leo_robinson_704,Leo,Robinsontypo,leo_robinson_704@example.com,819 Main St,Houston,NC,76672.0,France,...,(832)294-2916,2.0,Puzzle,Toys,235.47,2.0,470.94,2022-11-02,Bank Transfer,Refunded
2,1,leo_robinson_704,Leo,Robinson,leo_robinson_704@example.com,819 Main St,Houston,NC,76672.0,France,...,(832)294-2916,3.0,Pants,Clothing,105.77,1.0,105.77,2021-09-06,Credit Card,Cancelled
3,1,leo_robinson_704,Leo,Robinson,leo_robinson_704@example.com,819 Main St,Houston,NC,76672.0,France,...,(832)294-2916,0.0,Biography,Books,290.19,2.0,580.38,2022-10-20,Credit Card,Refunded
4,1,leo_robinson_704,Leo,Robinson,leo_robinson_704@example.com,819 Main St,Houston,NC,76672.0,France,...,(832)294-2916,5.0,Camera,Electronics,344.09,2.0,688.18,2021-05-18,Bank Transfer,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2599,500,jack_rodriguez_661,Jack,NaN,jack_rodriguez_661@example.com,7734 Main St,Dallas,CA,37181.0,USA,...,(689)156-2407,2559.0,Board Game,Toys,61.19,3.0,183.57,2025-04-20,Credit Card,Completed
2600,500,jack_rodriguez_661,Jack,Rodriguez,jack_rodriguez_661@example.com,7734 Main St,Dallas,CA,37181.0,USA,...,(689)156-2407,2560.0,Dress,Clothing,226.90,1.0,226.90,2023-07-09,PayPal,Completed
2601,500,jack_rodriguez_661,Jack,Rodriguez,jack_rodriguez_661@example.com,7734 Main St,Dallas,CA,37181.0,USA,...,(689)156-2407,2561.0,Camera,Electronics,17.11,0.0,34.22,2023-12-14,Bank Transfer,Cancelled
2602,500,jack_rodriguez_661,Jack,Rodriguez,jack_rodriguez_661@example.com,7734 Main St,Dallas,CA,18.0,USA,...,(689)156-2407,2562.0,Camera,Electronics,65.95,5.0,NaN,2025-02-02,Debit Card,Cancelled
2603,500,jack_rodriguez_661,Jack,Rodriguez,jack_rodriguez_661@example.com,7734 Main St,Dallas,CA,37181.0,USA,...,(689)156-2407,2563.0,Puzzle,Toys,397.19,1.0,397.19,2024-05-09,Cash on Delivery,Refunded

In [5]:
type(ecom['PurchaseDate'][0])

pandas.Timestamp

In [6]:
ecom['FullName'] = ecom['FirstName'] + ' ' + ecom['LastName']

ecom

,UserID,Username,FirstName,LastName,Email,Address,City,State,ZipCode,Country,...,PurchaseID,ProductName,Category,Price,Quantity,TotalAmount,PurchaseDate,PaymentMethod,Status,FullName
0,1,leo_robinson_704,Leo,Robinson,leo_robinson_704@example.com,819 Main St,Houston,NC,76672.0,France,...,1.0,Laptop,Electronics,43.21,1.0,43.21,2021-06-18,Bank Transfer,Pending,Leo Robinson
1,1,leo_robinson_704,Leo,Robinsontypo,leo_robinson_704@example.com,819 Main St,Houston,NC,76672.0,France,...,2.0,Puzzle,Toys,235.47,2.0,470.94,2022-11-02,Bank Transfer,Refunded,Leo Robinsontypo
2,1,leo_robinson_704,Leo,Robinson,leo_robinson_704@example.com,819 Main St,Houston,NC,76672.0,France,...,3.0,Pants,Clothing,105.77,1.0,105.77,2021-09-06,Credit Card,Cancelled,Leo Robinson
3,1,leo_robinson_704,Leo,Robinson,leo_robinson_704@example.com,819 Main St,Houston,NC,76672.0,France,...,0.0,Biography,Books,290.19,2.0,580.38,2022-10-20,Credit Card,Refunded,Leo Robinson
4,1,leo_robinson_704,Leo,Robinson,leo_robinson_704@example.com,819 Main St,Houston,NC,76672.0,France,...,5.0,Camera,Electronics,344.09,2.0,688.18,2021-05-18,Bank Transfer,Completed,Leo Robinson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2599,500,jack_rodriguez_661,Jack,NaN,jack_rodriguez_661@example.com,7734 Main St,Dallas,CA,37181.0,USA,...,2559.0,Board Game,Toys,61.19,3.0,183.57,2025-04-20,Credit Card,Completed,NaN
2600,500,jack_rodriguez_661,Jack,Rodriguez,jack_rodriguez_661@example.com,7734 Main St,Dallas,CA,37181.0,USA,...,2560.0,Dress,Clothing,226.90,1.0,226.90,2023-07-09,PayPal,Completed,Jack Rodriguez
2601,500,jack_rodriguez_661,Jack,Rodriguez,jack_rodriguez_661@example.com,7734 Main St,Dallas,CA,37181.0,USA,...,2561.0,Camera,Electronics,17.11,0.0,34.22,2023-12-14,Bank Transfer,Cancelled,Jack Rodriguez
2602,500,jack_rodriguez_661,Jack,Rodriguez,jack_rodriguez_661@example.com,7734 Main St,Dallas,CA,18.0,USA,...,2562.0,Camera,Electronics,65.95,5.0,NaN,2025-02-02,Debit Card,Cancelled,Jack Rodriguez
2603,500,jack_rodriguez_661,Jack,Rodriguez,jack_rodriguez_661@example.com,7734 Main St,Dallas,CA,37181.0,USA,...,2563.0,Puzzle,Toys,397.19,1.0,397.19,2024-05-09,Cash on Delivery,Refunded,Jack Rodriguez

In [10]:
for id in ecom['PurchaseID']:
    if id > 0:
        unique_cust_sum = ecom['FullName'].unique().size


print(f"Total number of total unique customers with greater than 0 purchases: {unique_cust_sum}")

Total number of total unique customers with greater than 0 purchases: 472